"""Daemon template schema. GENERATED by tools/extract_schema.py.

Required fields are authoritative (serde reports them).
observed_optional is NOT exhaustive: the daemon silently ignores
unknown fields, so there is no way to enumerate optional ones.
Regenerate after a daemon upgrade; do not hand-edit.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class VariantSpec:
    name: str
    required: tuple[str, ...]
    observed_optional: tuple[str, ...]


WIDGET_KINDS: dict[str, VariantSpec] = {
    'label': VariantSpec('label', ('text', 'font_size', 'color'), ('align', 'font', 'letter_spacing')),
    'value_text': VariantSpec('value_text', ('source', 'font_size', 'color'), ('align', 'font', 'format', 'letter_spacing', 'ranges', 'unit', 'value_max', 'value_min')),
    'radial_gauge': VariantSpec('radial_gauge', ('source', 'value_min', 'value_max', 'start_angle', 'sweep_angle', 'background_color'), ('bg_corner_radius', 'gradient', 'gradient_stops', 'inner_radius_pct', 'ranges', 'value_corner_radius')),
    'vertical_bar': VariantSpec('vertical_bar', ('source', 'value_min', 'value_max', 'background_color'), ('corner_radius', 'ranges')),
    'horizontal_bar': VariantSpec('horizontal_bar', ('source', 'value_min', 'value_max', 'background_color'), ('corner_radius', 'ranges')),
    'speedometer': VariantSpec('speedometer', ('source', 'value_min', 'value_max', 'start_angle', 'sweep_angle', 'needle_color', 'tick_color', 'background_color'), ()),
    'core_bars': VariantSpec('core_bars', ('background_color',), ()),
    'image': VariantSpec('image', ('path',), ()),
    'video': VariantSpec('video', ('path',), ()),
    'sparkline': VariantSpec('sparkline', ('source', 'value_min', 'value_max', 'background_color'), ('auto_range', 'axis_label_color', 'axis_label_count', 'axis_label_font', 'axis_label_format', 'axis_label_padding', 'axis_label_size', 'axis_labels_on_right', 'baseline_color', 'baseline_value', 'baseline_width', 'border_color', 'border_width', 'corner_radius', 'fill_color', 'fill_from_ranges', 'gridline_color', 'gridline_width', 'gridlines_horizontal', 'gridlines_vertical', 'history_length', 'line_color', 'line_width', 'padding', 'point_radius', 'range_blend', 'ranges', 'scroll_rtl', 'show_axis_labels', 'show_baseline', 'show_gridlines', 'show_points', 'smooth')),
    'clock_digital': VariantSpec('clock_digital', ('font_size', 'color'), ('align', 'font', 'format', 'letter_spacing')),
    'clock_analog': VariantSpec('clock_analog', (), ()),
}

SOURCE_TYPES: dict[str, VariantSpec] = {
    'constant': VariantSpec('constant', ('value',), ()),
    'command': VariantSpec('command', ('cmd',), ()),
    'hwmon': VariantSpec('hwmon', ('name', 'label'), ('device_path',)),
    'nvidia_gpu': VariantSpec('nvidia_gpu', (), ('gpu_index', 'metric')),
    'amd_gpu_usage': VariantSpec('amd_gpu_usage', (), ()),
    'wireless_coolant': VariantSpec('wireless_coolant', ('device_id',), ()),
    'cpu_usage': VariantSpec('cpu_usage', (), ()),
    'mem_usage': VariantSpec('mem_usage', (), ()),
    'mem_used': VariantSpec('mem_used', (), ()),
    'mem_free': VariantSpec('mem_free', (), ()),
    'network_rx': VariantSpec('network_rx', ('iface',), ()),
    'network_tx': VariantSpec('network_tx', ('iface',), ()),
    'disk_read': VariantSpec('disk_read', ('device',), ()),
    'disk_write': VariantSpec('disk_write', ('device',), ()),
}

KIND_NAMES = tuple(WIDGET_KINDS)
SOURCE_NAMES = tuple(SOURCE_TYPES)
